### ISSUE TITLE
Windows "Native' Script

### ISSUE THREAD

**Issue by scott-dunt** [elpy1/ssh-over-ssm#15]
Hoping to save others some time, I worked out a script for Windows (10) that works fairly well. The lack of a strong scripting engine (outside of PowerShell) makes this implementation more fragile than Linux.

the ProxyCommand Script I got working is:
```
rem Save this as  ssh4ssm.cmd
rem Usage ssh4ssm.cmd <instance ID> <user name> <AWS PROFILE NAME> <AWS Region>

set AWS_PROFILE=%3
set AWS_DEFAULT_REGION=%4

ssh-keygen -t ed25519 -N "" -f %USERPROFILE%\.ssh\ssm-ssh-tmp -C ssm-ssh-session
set /p ssh_pubkey= < %USERPROFILE%\.ssh\ssm-ssh-tmp.pub

set ssm_cmd="u=$(getent passwd %2) && x=$(echo $u |cut -d: -f6) || exit 1;install -d -m700 -o%2 ${x}/.ssh; grep \'%ssh_pubkey%\' ${x}/.ssh/authorized_keys && exit 1;printf \'%ssh_pubkey%\'|tee -a ${x}/.ssh/authorized_keys && sleep 30;sed -i s,\'%ssh_pubkey%\',, ${x}/.ssh/authorized_keys"

aws ssm send-command --instance-ids %1 --document-name AWS-RunShellScript --parameters commands='%ssm_cmd%' --comment "temporary ssm ssh access"

rem Bug Fix. the aws ssm start-session command exits the script completely, therefore any cleanup at the end of script never runs.
rem So, we fire off another process that waits for the session to get started and then it cleans up. Plus, the cleanup happens even if this script fails.

start /B \Windows\System32\cmd.exe /C "sleep 30 && del /F %USERPROFILE%\.ssh\ssm-ssh-tmp*"
aws ssm start-session --document-name AWS-StartSSHSession --target "%1"
```

We setup the `%USERPROFILE%\.ssh\config` file as:
```
Host *
  AddKeysToAgent No
  IdentityAgent none

Host AWS1
  Hostname i-<snip>
  User ubuntu
  ProxyCommand \Windows\System32\cmd.exe /C ssh4ssm.cmd %h %r <AWS Profile Name>  <AWS Region>
  IdentityFile ~/.ssh/ssm-ssh-tmp
```
It appears that the Windows / OpenSSH implementation reads the IdentityFile (if it exists) BEFORE it starts the proxycommand. Therefore if the file ~/.ssh/ssm-ssh-tmp or %USERPROFILE%\.ssh\ssm-ssh-tmp exists the connection will fail.

It also appears that the aws ssm start-session command on termination, exits the proxy script without running the remainder of the script.  Starting a separate command that sleeps for 30 seconds and then cleans up the key files finally corrected that issue. 
`start /B \Windows\System32\cmd.exe /C "sleep 30 && del /F %USERPROFILE%\.ssh\ssm-ssh-tmp*"`

that also seems to provide some fault tolerance because the separate process should always complete and clean up the key files.

**Comment by elpy1** [comment]
Thanks. Nice work - I'm sure others will find this useful.
