### ISSUE TITLE
AWS CLI 2.x requirement

### ISSUE THREAD

**Issue by cgill27** [elpy1/ssh-over-ssm#19]
It looks like ssh-over-ssm does not work with aws cli version 1.x, I needed to update to 2 for it to work.
May need to update the requirements to include that.

With aws cli version 1.x, the aws ssm wait command was not recognizing a parameter, here's a sample output:

+ aws ssm wait command-executed --instance-id <instance id> --command-id <command id>
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:

**Comment by elpy1** [comment]
Thanks. Good pick up - I'll update the README.

**Comment by elpy1** [comment]
Done https://github.com/elpy1/ssh-over-ssm/commit/ed21c2bb4b4928262545b08c01c66c07042dbff7
