### ISSUE TITLE
ssm_instances.py breaks on missing IPAddress

### ISSUE THREAD

**Issue by lousyd** [elpy1/ssh-over-ssm#2]
FYI. I tried running ssm_instances.py and it gave me an error:

```
lousyd $ AWS_PROFILE=lousyd python3 ssm_instances.py 
Traceback (most recent call last):
  File "ssm_instances.py", line 44, in <module>
    data = ssm_list_instances()
  File "ssm_instances.py", line 35, in ssm_list_instances
    ips = [x['IPAddress'] for x in ssmi]
  File "ssm_instances.py", line 35, in <listcomp>
    ips = [x['IPAddress'] for x in ssmi]
KeyError: 'IPAddress'
```
Stepping through the program, I saw that it was throwing an error when it tried to query the "IPAddress" field of the output of "ssm.describe_instance_information()" because that was returning data with the IPAddress missing in one JSON record. Amazon was returning that object with all the other fields, but not an IPAddress. Perhaps ssm_instances.py could be made to handle that exception. Ignore that record or something.

Just FYI. I don't need it fixed for me. Just wanted to let you know.

**Comment by elpy1** [comment]
Thanks for letting me know, definitely didn't think any instances would be without an IP!

I've just [committed](https://github.com/elpy1/ssh-over-ssm/commit/95795aaca7a5445e530de557d742e9eef478ad86) a change to address this - by using dict.get(), None will be returned if the dict Key doesn't exist. This should solve the error.
