### ISSUE TITLE
Fetch and use host key

### ISSUE THREAD

**Issue by sihil** [elpy1/ssh-over-ssm#21]
Rather than disabling strict host key checking it would be nicer to fetch the host key at the same time as pushing the identity key and using this.

I have previously implemented this in a similar project and did this by:
 - running something like `for hostkey in $$(grep ^HostKey $sshd_config_path| cut -d' ' -f 2); do cat $${hostkey}.pub; done` as part of the command to echo the host keys
 - choosing one of the returned keys using a list of preferred algorithms to find which to use (I defaulted this to "ecdsa-sha2-nistp256", "ssh-rsa" but recall some older hosts didn't have either)
 - write that host key to a temp file
 - specify `UserKnownHostsFile <tmpfile>`

I note that `IdentityFile` and `UserKnownHostsFile` support the `%h` token so perhaps the temp files could include that for better concurrent connection robustness?

It's possible I'll get to this at some stage, but thought I'd drop this here as a request anyway.

Thanks for your work on this project!

**Comment by elpy1** [comment]
Thanks for the comment and suggestion but I'm not sure this can be implemented easily or reliably. Also curious what security benefit it provides if we automatically fetch and update it on every connection? How would you know if the host's key has changed?

FYI no one is stopping you from using strict host key checking.

**Comment by sihil** [comment]
The reasoning being that we trust the SSM command fetching the host key. But by the same reasoning we also trust the SSM command establishing the tunnel so it doesn't provide any benefit. 

I recall now that this was implemented before SSM channels, so we were using SSM to exchange keys securely but creating an SSH connection over a network which is vulnerable to interception/proxying by an attacker. With the switch to channels this is no longer relevant so apologies for the noise.

**Comment by elpy1** [comment]
Not a problem!
