### ISSUE TITLE
works for me with an old version but not with the latest

### ISSUE THREAD

**Issue by kforner** [elpy1/ssh-over-ssm#23]
I have an old version which works fine. I wanted to update, but got:

```
 ./ssh-over-ssm/ssh-ssm.sh i-xxxxxxxxx ubuntu
no such identity: /home/karl/.ssh/ssm-ssh-tmp: No such file or directory
```

with the old version:
```
 ./ssh-ssm.sh i-xxxxxxx ubuntu
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.15.0-1015-aws x86_64)
```

The new version is commit c46b649af0c81a5481b6dea4d0969923a021788b
I tried and found the first commit which does not work for me. It is: b25496cac386b0dd521d17b28d73b04a7b474eac

It seems that the change that make it fails is from :

```
pr="$(grep -sl --exclude='*tool-env' "$1" "${ssh_dir}"/ssmtool-*)" &&
export AWS_PROFILE=${AWS_PROFILE:-${pr##*ssmtool-}}
```

to
```
 if pr="$(grep -sl --exclude='*tool-env' "$1" ${ssh_dir}/ssmtool-*)"; then
    export AWS_PROFILE=${AWS_PROFILE:-${pr##*ssmtool-}}
 fi
```
in `checks()`, probably because the exit status is modified. In the working case it is !=0, so that mktmpkey is called, whereas in the 
b25496cac386b0dd521d17b28d73b04a7b474eac commit, it's `ssh add -L` which is called.

**Comment by elpy1** [comment]
hey @kforner,

 Sorry for the delayed response, been super busy lately. Can you please try out the version at: https://github.com/elpy1/ssh-over-ssm/blob/hotfix/tmp-key-generation/ssh-ssm.sh

Let me know how it goes.

Thanks

**Comment by elpy1** [comment]
I've tested the changes and pushed them to `master`.  Closing this.
