### ISSUE TITLE
RunCommand to add SSH key flakes on Ubuntu shells

### ISSUE THREAD

**Issue by bradq** [elpy1/ssh-over-ssm#3]
Thanks for publishing your script! I wasn't aware of the socket capabilities of SSM, and adding in the ProxyCommand tie-in + ephemeral key generation let us plan to shut down SSH in a matter of days rather than months. 

The only issue I've run into across 300 machines is Ubuntu's processing of the RunCommand sed to inject the key into `authorized_keys`:

```
----------ERROR-------

/var/lib/amazon/ssm/i-xxxxxxxxxxxx/document/orchestration/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/awsrunShellScript/0.awsrunShellScript/_script.sh: 3: /var/lib/amazon/ssm/i-xxxxxxxxxxxxxx/document/orchestration/xxxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxxxx/awsrunShellScript/0.awsrunShellScript/_script.sh: Syntax error: redirection unexpected

failed to run commands: exit status 2
```

Ubuntu's `sh`, used by default, is dash rather than bash, which mucks the shell interpolation. Adding a shebang line to the RunCommand script doesn't appear to help, and I can't say I've run into this before. Posting in case you've run into the same, but I'll follow up with a fix here.

**Comment by elpy1** [comment]
Hi Brad, I haven't myself come across this but my first thought after you mentioned dash is the herestring `<<<` may be the issue. I can't do any testing myself at this moment but try updating with the following and see if the result is any different:

`u=\$(getent passwd ${ssh_user}) && x=\$(echo \$u |cut -d: -f6) || exit 1`
