### ISSUE TITLE
More of a 'cool' We can use zmodem to transfer files through the console

### ISSUE THREAD

**Issue by munntjlx** [elpy1/ssh-over-ssm#8]
If you configure your terminal to work with zmodem (lrzsz package) you can send files through the ssh terminal w/o having to shell out to sftp whatnot. It makes the shell script completely seamless for light file duty. just do 'rz' file and iterm2 picks up the zmodem request, prompts me for a filename (gui), and VOILA transferrs to the remote session w/o having to exit ssh! Only limitation is <=4gb file size.

**Comment by elpy1** [comment]
Very cool. Thanks for the info.
