### ISSUE TITLE
Keep getting permission denied errors

### ISSUE THREAD

**Issue by seemantk** [elpy1/ssh-over-ssm#9]
Hello!  I've recently switched to using ssm, and I really love the idea of this script.
When testing this afternoon, I ran it (configured for tmp ssh key).

The first two times I was prompted for a password.  Nothing worked (not blank, not O/S password, not aws password).  The third time onward, I now get this error:

`debug3: sign_and_send_pubkey: RSA SHA256:f7+oVbb4ho96mjodu8HBHnFbk0da2QJJ81pv+lk6YWo
debug3: sign_and_send_pubkey: signing using rsa-sha2-512 SHA256:f7+oVbb4ho96mjodu8HBHnFbk0da2QJJ81pv+lk6YWo
sign_and_send_pubkey: signing failed for RSA "seemant@arcii" from agent: agent refused operation
debug1: Trying private key: /home/seemant/.ssh/ssm-ssh-tmp
no such identity: /home/seemant/.ssh/ssm-ssh-tmp: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
`
Thank you

**Comment by elpy1** [comment]
This information looks important? -> `signing failed for RSA "seemant@arcii" from agent: agent refused operation debug1: Trying private key: `

Try checking permissions on your `~/.ssh` directory and key files (`chmod 600` for files, `700` for directories) and re-add to your ssh-agent with `ssh-add <key>`. Use `ssh-add -l` to confirm the key has been added to your agent.

FYI - no temp key will be created if a key is available via `ssh-agent`

**Comment by seemantk** [comment]
Thank you for taking a look.  Actually to me this information looks important: debug1: Trying private key: /home/seemant/.ssh/ssm-ssh-tmp
no such identity: /home/seemant/.ssh/ssm-ssh-tmp: No such file or directory

I am specifically wanting this script to generate the temporary key.  I'm unable to ssh-add the tmp key outside of this script, as it does not exist...

**Comment by elpy1** [comment]
That's expected. SSH looks for the key because of this in the SSH config -> `IdentityFile ~/.ssh/ssm-ssh-tmp`. However, by default the script will only generate a temporary key if there's none available to use from `ssh-agent`.
To change the logic and force a temp key to be created and used each time you'll need to modify the script as needed.

**Comment by seemantk** [comment]
Thank you.  It turned out that the error was due to the fact that I ctrl-c'd out of the passphrase for my own key.  ssh-agent was from then confused about everything.  Issuing a `keychain --clear` command and re-entering passphrase fixed it. Thank you again for your attention, your time, your howto and this utility.

Cheers!
